version: '3.9'
services:
  debug_client:
    container_name: debug_client 
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9001:80
    volumes: 
     - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
